import type { Metadata } from 'next';
import { LOCALES, assertLocale, dir } from '@stackd/shared';
import { BRAND, BRANCH } from '@stackd/shared';
// Generated by scripts/fetch-fonts.mjs. Imported before globals so the
// @font-face rules land ahead of anything that references those families.
import '../fonts.generated.css';
import '../globals.css';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { RestaurantSchema } from '../components/RestaurantSchema';

/**
 * This is the ROOT layout. There is no app/layout.tsx — in the App Router only
 * one layout may render <html>/<body>, and `lang`/`dir` differ per locale, so the
 * locale segment has to own it.
 *
 * The bare `/` path is redirected to a locale by .htaccess (see public/.htaccess),
 * because a static export has no middleware.
 */

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale: raw } = await params;
  const locale = assertLocale(raw);
  const isAr = locale === 'ar';

  const title = isAr
    ? `${BRAND.nameAr} | ${BRAND.nameEn} — الخبر الشمالية`
    : `${BRAND.nameEn} — Al Khobar Al Shamalia`;
  const description = isAr
    ? `${BRAND.taglineAr} مطعم دجاج ومأكولات شارع أمريكية في الخبر الشمالية. برجر، ستربس، وأطباق العماليق.`
    : `${BRAND.taglineEn} American street food and fried chicken in Al Khobar. Burgers, strips, and Giants.`;

  return {
    title,
    description,
    // Rendered relative because the final domain (stackd.com.sa) is not live yet.
    // Set metadataBase once DNS is pointed, so OG images resolve absolutely.
    alternates: {
      canonical: `/${locale}/`,
      languages: { ar: '/ar/', en: '/en/' },
    },
    openGraph: {
      title,
      description,
      type: 'website',
      locale: isAr ? 'ar_SA' : 'en_US',
      siteName: BRAND.nameEn,
    },
    other: {
      'geo.region': 'SA-04',
      'geo.placename': isAr ? BRANCH.cityAr : BRANCH.cityEn,
    },
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale: raw } = await params;
  const locale = assertLocale(raw);

  return (
    // suppressHydrationWarning applies to THIS element's attributes only, one
    // level deep — children are still fully hydration-checked.
    //
    // Browser extensions commonly stamp classes onto <html> before React loads
    // (Modernizr-style `no-touch`, dark-mode forcers, password managers). The
    // server cannot know about them, so React reports a mismatch it can never
    // reconcile. This is the fix Next and React both recommend for the case.
    <html lang={locale} dir={dir(locale)} suppressHydrationWarning>
      <head>
        {/* Preload only the two faces this locale actually renders. The
            @font-face rules carry unicode-range, so the browser would fetch the
            right subset regardless — preloading just removes the round trip
            that would otherwise flash fallback text first.
            An Arabic page never touches the Latin files, and vice versa. */}
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
          href={`/fonts/cairo-${locale === 'ar' ? 'arabic' : 'latin'}-400-900.woff2`}
        />
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
          href={`/fonts/tajawal-${locale === 'ar' ? 'arabic' : 'latin'}-900.woff2`}
        />
        <meta name="theme-color" content="#0e0f0d" />
      </head>
      <body>
        <RestaurantSchema locale={locale} />
        <Header locale={locale} />
        <main>{children}</main>
        <Footer locale={locale} />
      </body>
    </html>
  );
}
