/**
 * Downloads and self-hosts the Arabic display/body faces.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Both Tajawal and Cairo are SIL Open Font Licence, so self-hosting is
 * permitted; OFL requires the licence text to travel with the fonts, which this
 * script writes alongside them.
 *
 * Self-hosted rather than linked from the Google CDN because:
 *  - a third-party font request is the slowest thing on an otherwise static
 *    page served from Hostinger,
 *  - the Artifact preview's CSP blocks external hosts outright, so a CDN link
 *    would fall back silently — and a silent fallback on the Arabic side of a
 *    bilingual site is exactly the failure we are fixing.
 *
 * Only the `arabic` and `latin` subsets are kept. Google also ships cyrillic,
 * vietnamese and greek for these families and none of them are wanted here.
 */

import {
  writeFileSync,
  mkdirSync,
  existsSync,
  readdirSync,
  copyFileSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const fontDir = join(root, 'apps/web/public/fonts');

/** Google serves woff2 only to a UA it recognises as a modern browser. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['arabic', 'latin']);

const FAMILIES = [
  {
    // Display: geometric, confident, reads as a brand face at large sizes.
    name: 'Tajawal',
    query: 'Tajawal:wght@500;700;800;900',
    slug: 'tajawal',
  },
  {
    // Body: designed for running Arabic text, excellent at small sizes.
    // Requested as a range so Google returns ONE variable file per subset.
    name: 'Cairo',
    query: 'Cairo:wght@400..900',
    slug: 'cairo',
  },
];

async function get(url, binary = false) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return binary ? Buffer.from(await res.arrayBuffer()) : res.text();
}

/**
 * The css2 response interleaves `/* subset *\/` comments with @font-face blocks.
 * The comment immediately preceding a block names its subset.
 */
function parseFaces(css) {
  const faces = [];
  let subset = 'unknown';
  const re = /\/\*\s*([a-z-]+)\s*\*\/|@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    if (m[1]) {
      subset = m[1];
      continue;
    }
    const block = m[2];
    const pick = (k) => new RegExp(`${k}:\\s*([^;]+);`).exec(block)?.[1]?.trim();
    const url = /url\(([^)]+)\)/.exec(block)?.[1];
    if (!url) continue;
    faces.push({
      subset,
      family: pick('font-family')?.replace(/['"]/g, '') ?? '',
      weight: pick('font-weight') ?? '400',
      style: pick('font-style') ?? 'normal',
      unicodeRange: pick('unicode-range') ?? '',
      url,
    });
  }
  return faces;
}

mkdirSync(fontDir, { recursive: true });

const cssBlocks = [];
let downloaded = 0;
let totalBytes = 0;

for (const fam of FAMILIES) {
  const css = await get(
    `https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`,
  );
  const faces = parseFaces(css).filter((f) => KEEP_SUBSETS.has(f.subset));

  console.log(`\n${fam.name}: ${faces.length} face(s) after subset filter`);

  for (const f of faces) {
    // Variable faces carry a range like "400 900"; flatten it for the filename.
    const weightSlug = f.weight.replace(/\s+/g, '-');
    const file = `${fam.slug}-${f.subset}-${weightSlug}.woff2`;
    const dest = join(fontDir, file);

    if (!existsSync(dest)) {
      const buf = await get(f.url, true);
      writeFileSync(dest, buf);
      downloaded++;
      totalBytes += buf.length;
      console.log(`  + ${file}  ${(buf.length / 1024).toFixed(1)} kB`);
    } else {
      console.log(`  = ${file} (already present)`);
    }

    cssBlocks.push(
      [
        '@font-face {',
        `  font-family: '${f.family}';`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${file}') format('woff2');`,
        f.unicodeRange ? `  unicode-range: ${f.unicodeRange};` : '',
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    );
  }
}

const header = `/*
 * Self-hosted webfonts. GENERATED by scripts/fetch-fonts.mjs — do not edit.
 *
 * Tajawal (display) and Cairo (body), both SIL Open Font Licence 1.1.
 * Licence text: apps/web/public/fonts/OFL.txt
 *
 * Only the arabic and latin subsets are shipped. unicode-range lets the browser
 * download just the subset a page actually needs, so an English page never
 * fetches the Arabic file and vice versa.
 */

`;

// Written into app/ so Next bundles the @font-face rules into the main
// stylesheet — one fewer blocking request than a separate <link>. The url()
// paths stay absolute /fonts/... because the woff2 files are served from public/.
writeFileSync(
  join(root, 'apps/web/app/fonts.generated.css'),
  header + cssBlocks.join('\n\n') + '\n',
);

writeFileSync(
  join(fontDir, 'OFL.txt'),
  `Tajawal and Cairo are licensed under the SIL Open Font License, Version 1.1.

Tajawal — Copyright (c) Boutros International
Cairo — Copyright (c) The Cairo Project Authors

This Font Software is licensed under the SIL Open Font License, Version 1.1.
The full licence text is available at:
https://scripts.sil.org/OFL

PERMISSION & CONDITIONS (summary — the full licence governs):
Permission is granted, free of charge, to use, study, copy, merge, embed,
modify, redistribute, and sell modified and unmodified copies of the Font
Software, subject to the conditions in the licence. The Font Software may not
be sold by itself, and the copyright and licence notices must be retained.
`,
);

/*
 * Mirror into the admin app. Runs LAST, so OFL.txt above is already on disk and
 * the licence travels with the copies rather than lagging a run behind.
 *
 * The admin portal is otherwise happy on system fonts — it is a tool, not a
 * brand surface. The exception is the print studio at /signup-qr, which sets the
 * posters and the roll-up banner in Tajawal and sends them to a print shop. A
 * hand-copied set of font files would silently drift the next time this script
 * ran, and that failure surfaces as a 2-metre banner in the wrong typeface.
 *
 * The url() paths are already absolute /fonts/..., and each Next app serves its
 * own public/, so one stylesheet is correct in both without rewriting.
 */
// ⚠ EVERY APP THAT RENDERS ARABIC NEEDS THESE, and they are mirrored rather
// than hand-copied so they cannot drift on the next run of this script — a
// drifted font shows up as a heading set in the wrong typeface, which nobody
// notices until it is on a wall.
for (const app of ['apps/admin', 'apps/portal']) {
  const dir = join(root, app, 'public/fonts');
  mkdirSync(dir, { recursive: true });
  for (const file of readdirSync(fontDir)) {
    copyFileSync(join(fontDir, file), join(dir, file));
  }
  writeFileSync(join(root, app, 'app/fonts.generated.css'), header + cssBlocks.join('\n\n') + '\n');
}

console.log(
  `\nDone. ${downloaded} file(s) downloaded, ${(totalBytes / 1024).toFixed(1)} kB total.`,
);
console.log(
  `Wrote fonts.generated.css for apps/web, apps/admin and apps/portal, and ${join(fontDir, 'OFL.txt')}`,
);
